import { Manrope } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toast";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignOutUrl="/log-out" afterSignInUrl="/dashboard">
      <TooltipProvider>
        <html lang="en" className={`${manrope.variable} h-full antialiased`}>
          <body className="min-h-full flex flex-col">
            <main>{children}</main>
            <Toaster />
          </body>
        </html>
      </TooltipProvider>
    </ClerkProvider>
  );
}
